workspace_root: .
default_note_type: general
mcp_server:
  port: 3000
  log_level: info
search:
  index_enabled: true
  index_path: .flint-note/search-index.json
note_types:
  auto_create_directories: true
  require_descriptions: true
